### ISSUE TITLE
Mysterious message before test results

### ISSUE THREAD

**Issue by jferard** [jferard/fastods#117]
After the last test of fastods, and before the test results, I have this message:
```
Exception in thread "Thread-1" java.lang.AssertionError: 
  Unexpected method call Handler.close():
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:44)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
	at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:66)
	at $java.util.logging.Handler$$EnhancerByCGLIB$$820d11b1.close(<generated>)
	at java.util.logging.LogManager.resetLogger(LogManager.java:1346)
	at java.util.logging.LogManager.reset(LogManager.java:1332)
	at java.util.logging.LogManager$Cleaner.run(LogManager.java:239)
```

It appears only with:

     mvn clean verify

**Comment by jferard** [comment]
To narrow the issue:
* go in `fastods` directory
* run `JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64" mvn -DskipITs=true verify`

**Comment by jferard** [comment]
Minimal version that produces the message:

`JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64" mvn -DskipITs=true -Dtest=ContainerTest,OdsFactoryTest,ImmutableElementsFlusherTest verify`
