### ISSUE TITLE
Duplicate entry when saving empty file

### ISSUE THREAD

**Issue by jferard** [jferard/fastods#133]
When running:

    final NamedOdsFileWriter writer = odsFactory.createWriter(file);
    writer.save();

I get:

```
java.util.zip.ZipException: duplicate entry: Thumbnails/

	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
	at com.github.jferard.fastods.util.ZipUTF8WriterImpl.putNextEntry(ZipUTF8WriterImpl.java:97)
	at com.github.jferard.fastods.odselement.OdsElements.createEmptyElements(OdsElements.java:236)
	at com.github.jferard.fastods.NamedOdsDocument.save(NamedOdsDocument.java:280)
	at com.github.jferard.fastods.OdsFileDirectWriter.save(OdsFileDirectWriter.java:83)
```

This is probably related to the fact that the file is empty.

**Comment by jferard** [comment]
Two calls to `OdsElements.createEmptyElements`:

```
OdsFactory.createWriter()
NamedOdsDocument.prepareFlush()
OdsElements.prepare()
NamedOdsFileWriter.update(...)
ImmutableElementsFlusher.flushInto()
OdsElements.createEmptyElements()

```
And:

```
NamedOdsFileWriter.save()
OdsFileDirectWriter.save()
NamedOdsDocument.save()
OdsElements.createEmptyElements()
```
The latter seems to be unnecessary since the empty elements should be created at the beginning.
